// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartnersHub.InfraBase.Infrastructure.Persistence;

#nullable disable

namespace PartnersHub.InfraBase.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InfrabaseDbContext))]
    [Migration("20260125120000_ExpandAssetHistoryValues")]
    partial class ExpandAssetHistoryValues
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PartnersHub.InfraBase.Domain.Aggregates.AssetAggregate.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AssetCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("AssetTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssetTypeOther")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("CapacityPerAsset")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CapexEntryMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ConstructionCompletionQuarter")
                        .HasColumnType("int");

                    b.Property<int?>("ConstructionCompletionYear")
                        .HasColumnType("int");

                    b.Property<int?>("ConstructionStartingQuarter")
                        .HasColumnType("int");

                    b.Property<int?>("ConstructionStartingYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DevelopmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ExpectedDebt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ExpectedEquity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FundingModel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("IRR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsPifGuaranteesRequired")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRevenueGenerating")
                        .HasColumnType("bit");

                    b.Property<string>("OpexEntryMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("QuantityOfAsset")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SectorOther")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("SubSectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubSectorOther")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubmittedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenderingStage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UnitOfMeasurementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnitOfMeasurementOther")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InfraBase.Domain.Aggregates.AssetAggregate.AssetAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SharePointUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "IsDeleted");

                    b.ToTable("AssetAttachments", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InfraBase.Domain.Aggregates.AssetAggregate.AssetCapex", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "Year")
                        .IsUnique();

                    b.ToTable("AssetCapexDetails", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InfraBase.Domain.Aggregates.AssetAggregate.AssetHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("FieldsChanged")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "PerformedAt");

                    b.ToTable("AssetHistories", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InfraBase.Domain.Aggregates.AssetAggregate.AssetOpex", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssetId", "Year")
                        .IsUnique();

                    b.ToTable("AssetOpexDetails", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InfraBase.Domain.Aggregates.AssetAggregate.Asset", b =>
                {
                    b.OwnsOne("PartnersHub.InfraBase.Domain.ValueObjects.AssetDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("AssetId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(3000)
                                .HasColumnType("nvarchar(3000)")
                                .HasColumnName("Description");

                            b1.HasKey("AssetId");

                            b1.ToTable("Assets");

                            b1.WithOwner()
                                .HasForeignKey("AssetId");
                        });

                    b.OwnsOne("PartnersHub.InfraBase.Domain.ValueObjects.AssetName", "AssetName", b1 =>
                        {
                            b1.Property<Guid>("AssetId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("AssetName");

                            b1.HasKey("AssetId");

                            b1.ToTable("Assets");

                            b1.WithOwner()
                                .HasForeignKey("AssetId");
                        });

                    b.OwnsOne("PartnersHub.InfraBase.Domain.ValueObjects.LocationCity", "LocationCity", b1 =>
                        {
                            b1.Property<Guid>("AssetId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("LocationCity");

                            b1.HasKey("AssetId");

                            b1.ToTable("Assets");

                            b1.WithOwner()
                                .HasForeignKey("AssetId");
                        });

                    b.OwnsOne("PartnersHub.InfraBase.Domain.ValueObjects.RejectionReason", "RejectionReason", b1 =>
                        {
                            b1.Property<Guid>("AssetId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(3000)
                                .HasColumnType("nvarchar(3000)")
                                .HasColumnName("RejectionReason");

                            b1.HasKey("AssetId");

                            b1.ToTable("Assets");

                            b1.WithOwner()
                                .HasForeignKey("AssetId");
                        });

                    b.Navigation("AssetName")
                        .IsRequired();

                    b.Navigation("Description");

                    b.Navigation("LocationCity")
                        .IsRequired();

                    b.Navigation("RejectionReason");
                });

            modelBuilder.Entity("PartnersHub.InfraBase.Domain.Aggregates.AssetAggregate.AssetAttachment", b =>
                {
                    b.HasOne("PartnersHub.InfraBase.Domain.Aggregates.AssetAggregate.Asset", null)
                        .WithMany("Attachments")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PartnersHub.InfraBase.Domain.ValueObjects.AttachmentMetadata", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("AssetAttachmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ContentType");

                            b1.Property<string>("FileExtension")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("FileName");

                            b1.Property<long>("FileSizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("FileSizeInBytes");

                            b1.HasKey("AssetAttachmentId");

                            b1.ToTable("AssetAttachments");

                            b1.WithOwner()
                                .HasForeignKey("AssetAttachmentId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InfraBase.Domain.Aggregates.AssetAggregate.AssetCapex", b =>
                {
                    b.HasOne("PartnersHub.InfraBase.Domain.Aggregates.AssetAggregate.Asset", null)
                        .WithMany("CapexDetails")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InfraBase.Domain.Aggregates.AssetAggregate.AssetHistory", b =>
                {
                    b.HasOne("PartnersHub.InfraBase.Domain.Aggregates.AssetAggregate.Asset", null)
                        .WithMany("History")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InfraBase.Domain.Aggregates.AssetAggregate.AssetOpex", b =>
                {
                    b.HasOne("PartnersHub.InfraBase.Domain.Aggregates.AssetAggregate.Asset", null)
                        .WithMany("OpexDetails")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InfraBase.Domain.Aggregates.AssetAggregate.Asset", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("CapexDetails");

                    b.Navigation("History");

                    b.Navigation("OpexDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
