namespace PartnersHub.ConfigurationHub.Infrastructure.Persistence;

/// <summary>
/// Shared InfraBase lookup seed triples (Sector, SubSector, AssetType name).
/// Used both for database seeding and for lookup filtering without persisting extra mapping tables.
/// </summary>
internal static class InfraBaseLookupSeedData
{
    internal static IReadOnlyList<(string Sector, string SubSector, string Asset)> Triples { get; } = new[]
    {
        // Digital & Technology
        ("Digital & Technology", "Data Center", "Data Centre"),
        ("Digital & Technology", "Data Storage", "Data Storage"),
        ("Digital & Technology", "Data Transmission", "Data Transmission Network"),
        ("Digital & Technology", "Data Transmission", "Telecommunication towers"),
        ("Digital & Technology", "Data Transmission", "Fiber Optics"),
        ("Digital & Technology", "Data Transmission", "Cable‑Only Network"),
        ("Digital & Technology", "Other", "Other"),
        //("Digital & Technology", "N/A" , "N/A" ),

        // Enabling Works
        ("Enabling Works", "Earthwork", "Earthwork"),
        ("Enabling Works", "Ground improvement", "Ground Improvement"),
        ("Enabling Works", "Marine works", "Dredging"),
        ("Enabling Works", "Marine works", "Jetty / Pontoon"),
        ("Enabling Works", "Other", "Other"),
        //("Enabling Works", "N/A" , "N/A" ),

        // Energy & Power
        ("Energy & Power", "EV system", "EV Charging Station"),
        ("Energy & Power", "Power Distribution", "33 kV / 13.8 kV Underground Transmission Line"),
        ("Energy & Power", "Power Distribution", "33 kV Distribution Substation"),
        ("Energy & Power", "Power Distribution", "69 kV Distribution Substation"),
        ("Energy & Power", "Power Distribution", "13.8 kV Secondary Substation"),
        ("Energy & Power", "Power Distribution", "13.8 kV Ring‑Main Unit"),
        ("Energy & Power", "Power Distribution", "LV Equipment (Major Feeders)"),
        ("Energy & Power", "Power Transmission", "HV Network (High‑Voltage Lines)"),
        ("Energy & Power", "Power Transmission", "MV Network (Medium‑Voltage Lines)"),
        ("Energy & Power", "Power Distribution", "LV Network (Low‑Voltage Distribution)"),
        ("Energy & Power", "Power Distribution", "Utility Tunnel / Corridor"),
        ("Energy & Power", "Power Generation", "Fuel‑Based Power Plant"),
        ("Energy & Power", "Power Generation", "Coal‑Based Power Plant"),
        ("Energy & Power", "Power Generation", "Natural‑Gas Power Plant"),
        ("Energy & Power", "Power Generation", "Hydrogen Power Plant"),
        ("Energy & Power", "Power Generation", "Solar Power Plant"),
        ("Energy & Power", "Power Generation", "Wind Power Plant"),
        ("Energy & Power", "Power Generation", "Bio‑Fuel Power Plant"),
        ("Energy & Power", "Power Generation", "Stand‑by Generator"),
        ("Energy & Power", "Power Storage", "Battery Energy Storage System"),
        ("Energy & Power", "Power Transmission", "380 kV Overhead Transmission Line"),
        ("Energy & Power", "Power Transmission", "132 kV Overhead Transmission Line"),
        ("Energy & Power", "Power Transmission", "115 kV Overhead Transmission Line"),
        ("Energy & Power", "Power Transmission", "110 kV Overhead Transmission Line"),
        ("Energy & Power", "Power Transmission", "69 kV Overhead Transmission Line"),
        ("Energy & Power", "Power Transmission", "380 kV Underground Transmission Line"),
        ("Energy & Power", "Power Transmission", "132 kV Underground Transmission Line"),
        ("Energy & Power", "Power Transmission", "115 kV Underground Transmission Line"),
        ("Energy & Power", "Power Transmission", "110 kV Underground Transmission Line"),
        ("Energy & Power", "Power Transmission", "380 kV Bulk Substation"),
        ("Energy & Power", "Power Transmission", "132 kV Step‑Down Substation"),
        ("Energy & Power", "Power Transmission", "110 kV Step‑Down Substation"),
        ("Energy & Power", "Power Transmission", "Sub‑Sea Utility Infrastructure (cable & pipe)"),
        ("Energy & Power", "Other", "Other"),
        //("Energy & Power", "N/A" , "N/A"),

        // Industrial Infrastructure
        ("Industrial Infrastructure", "Fuel / Gas Facility", "Gas stations"),
        ("Industrial Infrastructure", "Industrial Cities & Zones", "Industrial Cities & Zones"),
        ("Industrial Infrastructure", "Manufacturing Plants", "Manufacturing Plants"),
        ("Industrial Infrastructure", "Gas", "Gas Networks"),
        ("Industrial Infrastructure", "Factories", "Factories"),
        ("Industrial Infrastructure", "Other", "Other"),
        //("Industrial Infrastructure", "N/A" , "N/A"),

        // Social Infrastructure
        ("Social Infrastructure", "Public Realm", "Park"),
        ("Social Infrastructure", "Public Realm", "Beach"),
        ("Social Infrastructure", "Public Realm", "Sea Front"),
        ("Social Infrastructure", "Public Realm", "Promenade"),
        ("Social Infrastructure", "Public Realm", "Soft‑scape (Land‑scaping)"),
        ("Social Infrastructure", "Public Realm", "Hard‑scape (Paving, Plazas)"),
        ("Social Infrastructure", "Public Realm", "Open Space"),
        ("Social Infrastructure", "Public Realm", "Sport Field"),
        ("Social Infrastructure", "Other", "Other"),
        //("Social Infrastructure", "N/A" , "N/A"),
        ("Social Infrastructure", "Marine", "Canal"),
        ("Social Infrastructure", "Marine", "Marina Berth"),
        ("Social Infrastructure", "Culture", "Exhibition Centers"),
        ("Social Infrastructure", "Culture", "Museums"),
        ("Social Infrastructure", "Culture", "Libraries"),
        ("Social Infrastructure", "Culture", "Opera Houses"),
        ("Social Infrastructure", "Education", "Private Schools"),
        ("Social Infrastructure", "Education", "Public Schools"),
        ("Social Infrastructure", "Education", "Private Universities"),
        ("Social Infrastructure", "Education", "Public Universities"),
        ("Social Infrastructure", "Education", "Training centers"),
        ("Social Infrastructure", "Education", "Students Accommodation"),
        ("Social Infrastructure", "Government", "Police stations"),
        ("Social Infrastructure", "Government", "Civil defense"),
        ("Social Infrastructure", "Government", "Post office"),
        ("Social Infrastructure", "Government", "Government buildings"),
        ("Social Infrastructure", "Health", "Private Hospitals"),
        ("Social Infrastructure", "Health", "Public Hospitals"),
        ("Social Infrastructure", "Health", "Clinics"),
        ("Social Infrastructure", "Health", "Elderly care"),
        ("Social Infrastructure", "Housing", "Staff Housing"),
        ("Social Infrastructure", "Housing", "Labour Accommodation"),
        ("Social Infrastructure", "Housing", "Construction Villages"),
        ("Social Infrastructure", "Religious", "Mosques"),
        ("Social Infrastructure", "Sport & Enter", "Stadiums"),
        ("Social Infrastructure", "Sport & Enter", "Theme Parks"),
        ("Social Infrastructure", "Sport & Enter", "Sport Centers"),

        // Transportation & Logistics
        ("Transportation & Logistics", "Ports", "Port Facility"),
        ("Transportation & Logistics", "Airports", "Airport Facility (runway & terminal)"),
        ("Transportation & Logistics", "Airports", "Cargo"),
        ("Transportation & Logistics", "Buses", "Stations"),
        ("Transportation & Logistics", "Buses", "Bus Network"),
        ("Transportation & Logistics", "Logistics", "Logistics Centers"),
        ("Transportation & Logistics", "Logistics", "Special Economic Zone"),
        ("Transportation & Logistics", "Logistics", "Storges"),
        ("Transportation & Logistics", "Ports", "Dry Ports"),
        ("Transportation & Logistics", "Ports", "Sea Ports"),
        ("Transportation & Logistics", "Rail", "Monorail"),
        ("Transportation & Logistics", "Rail", "Passenger"),
        ("Transportation & Logistics", "Rail", "Metro"),
        ("Transportation & Logistics", "Roads", "Highways"),
        ("Transportation & Logistics", "Roads", "Road Network (including upgrades)"),
        ("Transportation & Logistics", "Roads", "Interchange"),
        ("Transportation & Logistics", "Roads", "Bridge / Underpass / Culvert Structure"),
        ("Transportation & Logistics", "Roads", "Tunnel"),
        ("Transportation & Logistics", "Car Parking", "Car Parking"),
        ("Transportation & Logistics", "Other", "Other"),
        //("Transportation & Logistics", "N/A" , "N/A"),

        // Water & Waste
        ("Water & Waste", "District cooling", "District‑Cooling Plant"),
        ("Water & Waste", "District cooling", "Chilled‑Water Transmission Network"),
        ("Water & Waste", "District cooling", "Chilled‑Water Distibution Network"),
        ("Water & Waste", "District cooling", "Existing District‑Cooling Upgrade"),
        ("Water & Waste", "Irrigation", "Irrigation Transmission Network"),
        ("Water & Waste", "Irrigation", "Irrigation Distribution Network"),
        ("Water & Waste", "Potable water", "Sea‑Water RO Desalination Plant"),
        ("Water & Waste", "Potable water", "Well‑Water RO Desalination Plant"),
        ("Water & Waste", "Potable water", "Potable‑Water Transmission Network"),
        ("Water & Waste", "Potable water", "Existing Water‑Treatment Plant Upgrade"),
        ("Water & Waste", "Potable water", "Potable‑Water Chlorination Plant"),
        ("Water & Waste", "Potable water", "Potable‑Water Distribution Network"),
        ("Water & Waste", "Sewage", "Sewage‑Treatment Plant"),
        ("Water & Waste", "Sewage", "Sewage Transmission Network"),
        ("Water & Waste", "Sewage", "Sewage Distribution Network"),
        ("Water & Waste", "Sewage", "Existing Sewage‑Treatment Plant Upgrade"),
        ("Water & Waste", "Solid waste", "Solid Waste Transfer Station"),
        ("Water & Waste", "Solid waste", "Solid Waste Treatment Plant"),
        ("Water & Waste", "Solid waste", "Automated Waste Collection System"),
        ("Water & Waste", "Storm water", "Storm‑Water Storage Pond"),
        ("Water & Waste", "Storm water", "Bioretention Wetland System"),
        ("Water & Waste", "Storm water", "Storm‑Water Network"),
        ("Water & Waste", "Other", "Other"),
        //("Water & Waste", "N/A" , "N/A"),

        // Other
        ("Other", "Other", "Other"),

        // N/A
        //("N/A" , "N/A" , "N/A")
    };
}

