// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartnersHub.Synergy.Infrastructure.Persistence;

#nullable disable

namespace PartnersHub.Synergy.Infrastructure.Migrations
{
    [DbContext(typeof(SynergyDbContext))]
    [Migration("20251222150915_AddUserEmailInSuccessStory")]
    partial class AddUserEmailInSuccessStory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.OpportunityAggregate.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CollaborationRationale")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CollaborationRequirementOther")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactMobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("ExpectedOutcomeOther")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("IsAdminCreated")
                        .HasColumnType("bit");

                    b.Property<int>("OpportunityTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RejectedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<bool>("TermsAccepted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TermsAcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TermsAcceptedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermsAndConditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ThematicAreaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityTypeId");

                    b.HasIndex("ThematicAreaId");

                    b.ToTable("Opportunities", (string)null);
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.OpportunityAggregate.OpportunityAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SharePointUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.ToTable("OpportunityAttachments", (string)null);
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.OpportunityAggregate.OpportunityCollaborationRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CollaborationRequirementId")
                        .HasColumnType("int");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CollaborationRequirementId");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("OpportunityId", "CollaborationRequirementId")
                        .IsUnique();

                    b.ToTable("OpportunityCollaborationRequirements", (string)null);
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.OpportunityAggregate.OpportunityExpectedOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ExpectedOutcomeId")
                        .HasColumnType("int");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExpectedOutcomeId");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("OpportunityId", "ExpectedOutcomeId")
                        .IsUnique();

                    b.ToTable("OpportunityExpectedOutcomes", (string)null);
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.OpportunityAggregate.OpportunitySynergyCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CollaborationDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SynergyCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("SynergyCompanyId");

                    b.HasIndex("OpportunityId", "SynergyCompanyId")
                        .IsUnique();

                    b.ToTable("OpportunitySynergyCompanies", (string)null);
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.SuccessStoryAggregate.SuccessStory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CollaborationStatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RejectedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RejectedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SectorName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("SuccessStoryTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("TermsAccepted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("TermsAcceptedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("TermsAcceptedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermsAndConditionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SuccessStoryTypeId");

                    b.ToTable("SuccessStories", (string)null);
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.SuccessStoryAggregate.SuccessStoryAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SharePointUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("SuccessStoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("SuccessStoryId");

                    b.ToTable("SuccessStoryAttachments", (string)null);
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.SuccessStoryAggregate.SuccessStoryOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SuccessStoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("SuccessStoryId");

                    b.ToTable("SuccessStoryOpportunities", (string)null);
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.SuccessStoryAggregate.SuccessStorySynergyCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SuccessStoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SynergyCompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SuccessStoryId");

                    b.HasIndex("SynergyCompanyId");

                    b.HasIndex("SuccessStoryId", "SynergyCompanyId")
                        .IsUnique();

                    b.ToTable("SuccessStorySynergyCompanies", (string)null);
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.Synergy.Lookups.CollaborationRequirement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CollaborationRequirements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Technology transfer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Joint R&D"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Co-creation"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.Synergy.Lookups.ExpectedOutcome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExpectedOutcomes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Revenue growth"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cost savings"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Increased Efficiency"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.Synergy.Lookups.OpportunityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OpportunityTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sponsorship"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Commercial Collaboration"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Strategic Collaboration"
                        });
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.Synergy.Lookups.SuccessStoryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SuccessStoryTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Partnership"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Collaboration"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Joint Venture"
                        });
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.Synergy.Lookups.ThematicArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ThematicAreas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ESG"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Digital Transformation"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Innovation"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sustainability"
                        });
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.SynergyCompanyAggregate.SynergyCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HeadquarterCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HeadquarterCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("SynergyCompanies", (string)null);
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.SynergyCompanyAggregate.SynergyCompanySector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SectorId");

                    b.HasIndex("CompanyId", "SectorId")
                        .IsUnique();

                    b.ToTable("SynergyCompanySectors", (string)null);
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.OpportunityAggregate.Opportunity", b =>
                {
                    b.HasOne("PartnersHub.Synergy.Domain.Aggregates.Synergy.Lookups.OpportunityType", "OpportunityType")
                        .WithMany()
                        .HasForeignKey("OpportunityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartnersHub.Synergy.Domain.Aggregates.Synergy.Lookups.ThematicArea", "ThematicArea")
                        .WithMany()
                        .HasForeignKey("ThematicAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PartnersHub.Synergy.Domain.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("OpportunityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(5000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.HasKey("OpportunityId");

                            b1.ToTable("Opportunities");

                            b1.WithOwner()
                                .HasForeignKey("OpportunityId");
                        });

                    b.OwnsOne("PartnersHub.Synergy.Domain.ValueObjects.RepresentativeInformation", "RepresentativeInformation", b1 =>
                        {
                            b1.Property<Guid>("OpportunityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("RepresentativeEmail");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("RepresentativeName");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("RepresentativePhone");

                            b1.Property<string>("Position")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("RepresentativePosition");

                            b1.HasKey("OpportunityId");

                            b1.ToTable("Opportunities");

                            b1.WithOwner()
                                .HasForeignKey("OpportunityId");
                        });

                    b.OwnsOne("PartnersHub.Synergy.Domain.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("OpportunityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("Title");

                            b1.HasKey("OpportunityId");

                            b1.ToTable("Opportunities");

                            b1.WithOwner()
                                .HasForeignKey("OpportunityId");
                        });

                    b.OwnsOne("PartnersHub.Synergy.Domain.ValueObjects.Sector", "Sector", b1 =>
                        {
                            b1.Property<Guid>("OpportunityId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("SectorId");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("SectorName");

                            b1.HasKey("OpportunityId");

                            b1.ToTable("Opportunities");

                            b1.WithOwner()
                                .HasForeignKey("OpportunityId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("OpportunityType");

                    b.Navigation("RepresentativeInformation")
                        .IsRequired();

                    b.Navigation("Sector")
                        .IsRequired();

                    b.Navigation("ThematicArea");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.OpportunityAggregate.OpportunityAttachment", b =>
                {
                    b.HasOne("PartnersHub.Synergy.Domain.Aggregates.OpportunityAggregate.Opportunity", null)
                        .WithMany("Attachments")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.OpportunityAggregate.OpportunityCollaborationRequirement", b =>
                {
                    b.HasOne("PartnersHub.Synergy.Domain.Aggregates.OpportunityAggregate.Opportunity", null)
                        .WithMany("CollaborationRequirements")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.OpportunityAggregate.OpportunityExpectedOutcome", b =>
                {
                    b.HasOne("PartnersHub.Synergy.Domain.Aggregates.OpportunityAggregate.Opportunity", null)
                        .WithMany("ExpectedOutcomes")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.OpportunityAggregate.OpportunitySynergyCompany", b =>
                {
                    b.HasOne("PartnersHub.Synergy.Domain.Aggregates.OpportunityAggregate.Opportunity", null)
                        .WithMany("CollaboratedCompanies")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.SuccessStoryAggregate.SuccessStory", b =>
                {
                    b.HasOne("PartnersHub.Synergy.Domain.Aggregates.Synergy.Lookups.SuccessStoryType", "SuccessStoryType")
                        .WithMany()
                        .HasForeignKey("SuccessStoryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PartnersHub.Synergy.Domain.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("SuccessStoryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(5000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.HasKey("SuccessStoryId");

                            b1.ToTable("SuccessStories");

                            b1.WithOwner()
                                .HasForeignKey("SuccessStoryId");
                        });

                    b.OwnsOne("PartnersHub.Synergy.Domain.ValueObjects.Title", "Title", b1 =>
                        {
                            b1.Property<Guid>("SuccessStoryId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)")
                                .HasColumnName("Title");

                            b1.HasKey("SuccessStoryId");

                            b1.ToTable("SuccessStories");

                            b1.WithOwner()
                                .HasForeignKey("SuccessStoryId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("SuccessStoryType");

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.SuccessStoryAggregate.SuccessStoryAttachment", b =>
                {
                    b.HasOne("PartnersHub.Synergy.Domain.Aggregates.SuccessStoryAggregate.SuccessStory", null)
                        .WithMany("Attachments")
                        .HasForeignKey("SuccessStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.SuccessStoryAggregate.SuccessStoryOpportunity", b =>
                {
                    b.HasOne("PartnersHub.Synergy.Domain.Aggregates.OpportunityAggregate.Opportunity", null)
                        .WithMany("SuccessStoryOpportunities")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartnersHub.Synergy.Domain.Aggregates.SuccessStoryAggregate.SuccessStory", null)
                        .WithMany("AssociatedOpportunities")
                        .HasForeignKey("SuccessStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.SuccessStoryAggregate.SuccessStorySynergyCompany", b =>
                {
                    b.HasOne("PartnersHub.Synergy.Domain.Aggregates.SuccessStoryAggregate.SuccessStory", null)
                        .WithMany("CollaboratedProfiles")
                        .HasForeignKey("SuccessStoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.SynergyCompanyAggregate.SynergyCompany", b =>
                {
                    b.OwnsOne("PartnersHub.Synergy.Domain.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("SynergyCompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(5000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.HasKey("SynergyCompanyId");

                            b1.ToTable("SynergyCompanies");

                            b1.WithOwner()
                                .HasForeignKey("SynergyCompanyId");
                        });

                    b.OwnsOne("PartnersHub.Synergy.Domain.ValueObjects.RepresentativeInformation", "RepresentativeInformation", b1 =>
                        {
                            b1.Property<Guid>("SynergyCompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Email");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("RepresentativeName");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Phone");

                            b1.Property<string>("Position")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Position");

                            b1.HasKey("SynergyCompanyId");

                            b1.ToTable("SynergyCompanies");

                            b1.WithOwner()
                                .HasForeignKey("SynergyCompanyId");
                        });

                    b.OwnsOne("PartnersHub.Synergy.Domain.ValueObjects.CompanyName", "Name", b1 =>
                        {
                            b1.Property<Guid>("SynergyCompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Name");

                            b1.HasKey("SynergyCompanyId");

                            b1.ToTable("SynergyCompanies");

                            b1.WithOwner()
                                .HasForeignKey("SynergyCompanyId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("RepresentativeInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.SynergyCompanyAggregate.SynergyCompanySector", b =>
                {
                    b.HasOne("PartnersHub.Synergy.Domain.Aggregates.SynergyCompanyAggregate.SynergyCompany", null)
                        .WithMany("Sectors")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.OpportunityAggregate.Opportunity", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("CollaboratedCompanies");

                    b.Navigation("CollaborationRequirements");

                    b.Navigation("ExpectedOutcomes");

                    b.Navigation("SuccessStoryOpportunities");
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.SuccessStoryAggregate.SuccessStory", b =>
                {
                    b.Navigation("AssociatedOpportunities");

                    b.Navigation("Attachments");

                    b.Navigation("CollaboratedProfiles");
                });

            modelBuilder.Entity("PartnersHub.Synergy.Domain.Aggregates.SynergyCompanyAggregate.SynergyCompany", b =>
                {
                    b.Navigation("Sectors");
                });
#pragma warning restore 612, 618
        }
    }
}
