// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PartnersHub.InnovationHub.Infrastructure.Presistence;

#nullable disable

namespace PartnersHub.InnovationHub.Infrastructure.Migrations
{
    [DbContext(typeof(InnovationHubDbContext))]
    [Migration("20251222131036_AddUserEmailInChallengeRequestAndCampaignRequest")]
    partial class AddUserEmailInChallengeRequestAndCampaignRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.CampaignRequest.CampaignTrackingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CampaignRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comments")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("FieldsChanged")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NewValues")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OldValues")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PerformedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("CampaignRequestId");

                    b.ToTable("CampaignTrackingHistory", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CampaignRequestStatus")
                        .HasColumnType("int")
                        .HasColumnName("CampaignRequestStatus");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Comments");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasColumnName("Description");

                    b.Property<DateTime?>("LaunchDate")
                        .HasColumnType("datetime")
                        .HasColumnName("LaunchDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OwnerName");

                    b.Property<string>("ProblemStatement")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasColumnName("ProblemStatement");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<long>("ShortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ShortId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ShortId"));

                    b.Property<DateTime?>("SubmissionDeadLine")
                        .HasColumnType("datetime")
                        .HasColumnName("SubmissionDeadLine");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CampaignRequests", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequestEvaluationCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CriteriaName")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("CriteriaValue")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CampaignRequestId");

                    b.ToTable("CampaignRequestEvaluationCriteria", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequestEvaluator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CampaignRequestId");

                    b.ToTable("CampaignRequestEvaluator", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequestLinkedChallenge", b =>
                {
                    b.Property<Guid>("CampaignRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("CampaignRequestId", "ChallengeRequestId");

                    b.HasIndex("ChallengeRequestId");

                    b.ToTable("CampaignRequestLinkedChallenges", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequestSponsor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SponserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<Guid>("SponsorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampaignRequestId");

                    b.ToTable("CampaignRequestSponsors", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequestTermsAndCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CampaignRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SharePointFileId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SharePointLibrary")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SharePointUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CampaignRequestId")
                        .HasDatabaseName("IX_CampaignRequestCampaignRequestTermsAndConditions_CampaignRequestId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_CampaignRequestCampaignRequestTermsAndConditions_IsDeleted");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("IX_CampaignRequestCampaignRequestTermsAndConditions_UploadedAt");

                    b.HasIndex("CampaignRequestId", "IsDeleted")
                        .HasDatabaseName("IX_CampaignRequestCampaignRequestTermsAndConditions_CampaignRequestId_IsDeleted");

                    b.ToTable("CampaignRequestTermsAndConditions", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssociatedSectorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AssociatedSectorId");

                    b.Property<int>("ChallengeStatus")
                        .HasColumnType("int")
                        .HasColumnName("ChallengeStatus");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)")
                        .HasColumnName("Description");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDraft")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.Property<int>("PriorityLevelId")
                        .HasColumnType("int")
                        .HasColumnName("PriorityLevelId");

                    b.Property<long>("ShortId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ShortId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ShortId"));

                    b.Property<Guid>("SourceCompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("SourceCompanyId");

                    b.Property<string>("SubmitterName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SubmitterName");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AssociatedSectorId");

                    b.HasIndex("SourceCompanyId");

                    b.ToTable("ChallengeRequests", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequestAssociatedProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("AssociatedProviders", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequestAssociatedSector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("AssociatedSectors", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequestAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SharePointFileId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SharePointLibrary")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SharePointUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeRequestId")
                        .HasDatabaseName("IX_ChallengeRequestAttachments_ChallengeRequestId");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_ChallengeRequestAttachments_IsDeleted");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("IX_ChallengeRequestAttachments_UploadedAt");

                    b.HasIndex("ChallengeRequestId", "IsDeleted")
                        .HasDatabaseName("IX_ChallengeRequestAttachments_ChallengeRequestId_IsDeleted");

                    b.ToTable("ChallengeRequestAttachments", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequestRevisionComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ChallengeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CommentedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeRequestId");

                    b.ToTable("challengeRequestRevisionComments");
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeTrackingHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.ToTable("challengeTrackingHistories", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeTechnologiesRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChallengeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JustificationForLinking")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("RequestStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TechnologyId");

                    b.HasIndex("ChallengeRequestId", "TechnologyId")
                        .IsUnique();

                    b.ToTable("challengeTechnologiesRequests");
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Lookups.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadquarterCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HeadquarterCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Lookups.CompanySector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SectorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("SectorId");

                    b.HasIndex("CompanyId", "SectorId")
                        .IsUnique();

                    b.ToTable("CompanySectors", (string)null);
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Lookups.Evaluator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Evaluators");
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Lookups.Sponsor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TechnologyStage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("technologies");
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.CampaignRequest.CampaignTrackingHistory", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequest", null)
                        .WithMany("TrackingHistory")
                        .HasForeignKey("CampaignRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequestEvaluationCriteria", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequest", null)
                        .WithMany("EvaluationCriterias")
                        .HasForeignKey("CampaignRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequestEvaluator", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequest", null)
                        .WithMany("Evaluators")
                        .HasForeignKey("CampaignRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequestLinkedChallenge", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequest", null)
                        .WithMany("LinkedChallenges")
                        .HasForeignKey("CampaignRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequest", null)
                        .WithMany("CampaignRequests")
                        .HasForeignKey("ChallengeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequestSponsor", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequest", null)
                        .WithMany("Sponsors")
                        .HasForeignKey("CampaignRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequestTermsAndCondition", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequest", null)
                        .WithMany("TermsAndCondition")
                        .HasForeignKey("CampaignRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PartnersHub.InnovationHub.Domain.ValueObjects.Attachment", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("CampaignRequestTermsAndConditionId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Extension")
                                .HasMaxLength(10)
                                .HasColumnType("int")
                                .HasColumnName("FileExtension");

                            b1.Property<int>("Format")
                                .HasMaxLength(100)
                                .HasColumnType("int")
                                .HasColumnName("FileFormat");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("FileName");

                            b1.Property<long>("SizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("FileSizeInBytes");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CampaignRequestTermsAndConditionId");

                            b1.ToTable("CampaignRequestTermsAndConditions");

                            b1.WithOwner()
                                .HasForeignKey("CampaignRequestTermsAndConditionId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequest", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequestAssociatedSector", "AssociatedSector")
                        .WithMany()
                        .HasForeignKey("AssociatedSectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequestAssociatedProvider", "SourceCompany")
                        .WithMany()
                        .HasForeignKey("SourceCompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssociatedSector");

                    b.Navigation("SourceCompany");
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequestAttachment", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequest", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ChallengeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("PartnersHub.InnovationHub.Domain.ValueObjects.Attachment", "Metadata", b1 =>
                        {
                            b1.Property<Guid>("ChallengeRequestAttachmentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Extension")
                                .HasMaxLength(10)
                                .HasColumnType("int")
                                .HasColumnName("FileExtension");

                            b1.Property<int>("Format")
                                .HasMaxLength(100)
                                .HasColumnType("int")
                                .HasColumnName("FileFormat");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(255)
                                .HasColumnType("nvarchar(255)")
                                .HasColumnName("FileName");

                            b1.Property<long>("SizeInBytes")
                                .HasColumnType("bigint")
                                .HasColumnName("FileSizeInBytes");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ChallengeRequestAttachmentId");

                            b1.ToTable("ChallengeRequestAttachments");

                            b1.WithOwner()
                                .HasForeignKey("ChallengeRequestAttachmentId");
                        });

                    b.Navigation("Metadata")
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequestRevisionComment", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequest", null)
                        .WithMany("RevisionComments")
                        .HasForeignKey("ChallengeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeTrackingHistory", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequest", null)
                        .WithMany("TrackingHistory")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeTechnologiesRequest", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequest", null)
                        .WithMany("Technologies")
                        .HasForeignKey("ChallengeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.Technology", "LinkedTechnology")
                        .WithMany()
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LinkedTechnology");
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Lookups.Company", b =>
                {
                    b.OwnsOne("PartnersHub.InnovationHub.Domain.ValueObjects.CompanyName", "Name", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("Name");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("PartnersHub.InnovationHub.Domain.ValueObjects.Description", "Description", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Value")
                                .HasMaxLength(5000)
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Description");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.OwnsOne("PartnersHub.InnovationHub.Domain.ValueObjects.RepresentativeInformation", "RepresentativeInformation", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("nvarchar(256)")
                                .HasColumnName("Email");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("RepresentativeName");

                            b1.Property<string>("Phone")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Phone");

                            b1.Property<string>("Position")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Position");

                            b1.HasKey("CompanyId");

                            b1.ToTable("Companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("RepresentativeInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Lookups.CompanySector", b =>
                {
                    b.HasOne("PartnersHub.InnovationHub.Domain.Aggregates.Lookups.Company", null)
                        .WithMany("Sectors")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Campaigns.CampaignRequest", b =>
                {
                    b.Navigation("EvaluationCriterias");

                    b.Navigation("Evaluators");

                    b.Navigation("LinkedChallenges");

                    b.Navigation("Sponsors");

                    b.Navigation("TermsAndCondition");

                    b.Navigation("TrackingHistory");
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.ChallengeRequest.ChallengeRequest", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("CampaignRequests");

                    b.Navigation("RevisionComments");

                    b.Navigation("Technologies");

                    b.Navigation("TrackingHistory");
                });

            modelBuilder.Entity("PartnersHub.InnovationHub.Domain.Aggregates.Lookups.Company", b =>
                {
                    b.Navigation("Sectors");
                });
#pragma warning restore 612, 618
        }
    }
}
